"""cascade report slide deletes

Revision ID: 69b150cbb182
Revises: 7fc858f5fa07
Create Date: 2026-07-01 01:42:06.698754

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "69b150cbb182"
down_revision: Union[str, Sequence[str], None] = "7fc858f5fa07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("slide_shares_slide_id_fkey"), "slide_shares", type_="foreignkey")
    op.create_foreign_key(None, "slide_shares", "slides", ["slide_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("slides_report_id_fkey"), "slides", type_="foreignkey")
    op.create_foreign_key(None, "slides", "reports", ["report_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slides", type_="foreignkey")
    op.create_foreign_key(op.f("slides_report_id_fkey"), "slides", "reports", ["report_id"], ["id"])
    op.drop_constraint(None, "slide_shares", type_="foreignkey")
    op.create_foreign_key(
        op.f("slide_shares_slide_id_fkey"), "slide_shares", "slides", ["slide_id"], ["id"]
    )
    # ### end Alembic commands ###
