"""add slide_shares table

Revision ID: 78f36e07fabc
Revises: a3ce8f557b8e
Create Date: 2026-06-30 22:23:08.513375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f36e07fabc'
down_revision: Union[str, Sequence[str], None] = 'a3ce8f557b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('slide_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_shares_organization_id'), 'slide_shares', ['organization_id'], unique=False)
    op.create_index(op.f('ix_slide_shares_slide_id'), 'slide_shares', ['slide_id'], unique=False)
    op.create_index(op.f('ix_slide_shares_token'), 'slide_shares', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slide_shares_token'), table_name='slide_shares')
    op.drop_index(op.f('ix_slide_shares_slide_id'), table_name='slide_shares')
    op.drop_index(op.f('ix_slide_shares_organization_id'), table_name='slide_shares')
    op.drop_table('slide_shares')
    # ### end Alembic commands ###
