"""make owner ids nullable on user delete

Revision ID: 7fc858f5fa07
Revises: 78f36e07fabc
Create Date: 2026-07-01 00:18:38.262301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fc858f5fa07"
down_revision: Union[str, Sequence[str], None] = "78f36e07fabc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reports", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("reports_owner_id_fkey"), "reports", type_="foreignkey")
    op.create_foreign_key(None, "reports", "users", ["owner_id"], ["id"], ondelete="SET NULL")
    op.add_column("slide_shares", sa.Column("owner_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("slide_shares_created_by_user_id_fkey"), "slide_shares", type_="foreignkey"
    )
    op.create_foreign_key(None, "slide_shares", "users", ["owner_id"], ["id"], ondelete="SET NULL")
    op.drop_column("slide_shares", "created_by_user_id")
    op.alter_column("slides", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("slides_owner_id_fkey"), "slides", type_="foreignkey")
    op.create_foreign_key(None, "slides", "users", ["owner_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slides", type_="foreignkey")
    op.create_foreign_key(op.f("slides_owner_id_fkey"), "slides", "users", ["owner_id"], ["id"])
    op.alter_column("slides", "owner_id", existing_type=sa.UUID(), nullable=False)
    op.add_column(
        "slide_shares",
        sa.Column("created_by_user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "slide_shares", type_="foreignkey")
    op.create_foreign_key(
        op.f("slide_shares_created_by_user_id_fkey"),
        "slide_shares",
        "users",
        ["created_by_user_id"],
        ["id"],
    )
    op.drop_column("slide_shares", "owner_id")
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.create_foreign_key(op.f("reports_owner_id_fkey"), "reports", "users", ["owner_id"], ["id"])
    op.alter_column("reports", "owner_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
